
/ as sysdba
SELECT to_char(sysdate,'DD MM YYYY Year Month Day HH:MI:SS Am') FROM dual;
DROP USER c##lennin_L4Q1 CASCADE;
CREATE USER c##lennin_L4Q1 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO c##lennin_L4Q1;
ALTER USER c##lennin_L4Q1 QUOTA 100M on users;
CONNECT c##lennin_L4Q1/123;

SPOOL C:\Users\lenni\Escritorio\SPOOL.txt

CREATE TABLE CUSTOMER (
    CustID NUMBER,
    CustName VARCHAR2(50),
    Phone NUMBER
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CustID_PK PRIMARY KEY(CustID);

CREATE TABLE ORDERS(
    OID NUMBER,
    Odate DATE,
    CustID NUMBER
);

ALTER TABLE ORDERS
ADD CONSTRAINT OID_PK PRIMARY KEY(OID);

ALTER TABLE ORDERS
ADD CONSTRAINT CustID_FK FOREIGN KEY (CustID) REFERENCES CUSTOMER (CustID);

CREATE TABLE PRODUCT (
    ProductID NUMBER,
    Description VARCHAR2(50),
    Price NUMBER
);

ALTER TABLE PRODUCT
ADD CONSTRAINT ProductID_PK PRIMARY KEY(ProductID);

CREATE TABLE ORDER_LINE(
    ProductID NUMBER,
    OID NUMBER,
    Quantity NUMBER
);

ALTER TABLE ORDER_LINE
ADD CONSTRAINT ProductID_OID_PK PRIMARY KEY (ProductID, OID);

ALTER TABLE ORDER_LINE
ADD CONSTRAINT ProductID_FK FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID);

ALTER TABLE ORDER_LINE
ADD CONSTRAINT OID_FK FOREIGN KEY (OID) REFERENCES ORDERS (OID);

CREATE TABLE SUPPLIER (
    Supplier_ID NUMBER,
    Supplier_Name VARCHAR2(50)
);

ALTER TABLE SUPPLIER
ADD CONSTRAINT Supplier_ID_PK PRIMARY KEY (Supplier_ID);

ALTER TABLE CUSTOMER
MODIFY (CustName VARCHAR2(50) NOT NULL);

ALTER TABLE PRODUCT
MODIFY (Description VARCHAR2(50) NOT NULL);

ALTER TABLE PRODUCT
ADD CONSTRAINT Price_GT_0 CHECK (Price > 0);


DESC LOCATION
DESC ORDERS
DESC PRODUCT
DESC ORDER_LINE
DESC SUPPLIER;

SELECT table_name, column_name, data_type, data_length
FROM user_tab_columns;

SELECT constraint_name, constraint_type
FROM user_constraints;

SPOOL OFF;
