/ as sysdba
SELECT to_char(sysdate,'DD MM YYYY Year Month Day HH:MI:SS AM') FROM dual;

DROP USER c##lennin_L5Q1 CASCADE;
CREATE USER c##lennin_L5Q1 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO c##lennin_L5Q1;
ALTER USER c##lennin_L5Q1 QUOTA 100M on users;
CONNECT c##lennin_L5Q1/123;

SPOOL C:\Users\lenni\Escritorio\SPOOLA.txt


CREATE TABLE COURSE(
    CourseID NUMBER,
    CourseName VARCHAR2(10),
    Credits NUMBER
);

CREATE TABLE TERM(
    TermID NUMBER,
    Descriptionn VARCHAR2(10),
    Status VARCHAR2(10)
);

CREATE TABLE LOCATION(
    LocID NUMBER,
    Building VARCHAR2(10),
    Room NUMBER
);

CREATE TABLE STUDENT(
    StudID NUMBER,
    SName VARCHAR2(10),
    Birthdate DATE
);

CREATE TABLE ENROLLMENT(
    StudID NUMBER,
    CSectionID NUMBER,
    GRADE NUMBER
);

CREATE TABLE COURSE_SECTION(
    CSectionID NUMBER,
    MaxCapacity NUMBER,
    CourseID NUMBER,
    TermID NUMBER,
    LocID NUMBER
);

ALTER TABLE COURSE ADD CONSTRAINT CourseID_PK PRIMARY KEY (CourseID);
ALTER TABLE TERM ADD CONSTRAINT TermID_PK PRIMARY KEY (TermID);
ALTER TABLE LOCATION ADD CONSTRAINT LocID_PK PRIMARY KEY (LocID);
ALTER TABLE STUDENT ADD CONSTRAINT StudID_PK PRIMARY KEY (StudID);
ALTER TABLE COURSE_SECTION ADD CONSTRAINT CSectionID_PK PRIMARY KEY (CSectionID);

ALTER TABLE ENROLLMENT ADD CONSTRAINT StudID_FK FOREIGN KEY (StudID) REFERENCES STUDENT (StudID);
ALTER TABLE ENROLLMENT ADD CONSTRAINT CSectionID_FK FOREIGN KEY (CSectionID) REFERENCES COURSE_SECTION (CSectionID);
ALTER TABLE COURSE_SECTION ADD CONSTRAINT CourseID_FK FOREIGN KEY (CourseID) REFERENCES COURSE (CourseID);
ALTER TABLE COURSE_SECTION ADD CONSTRAINT TermID_FK FOREIGN KEY (TermID) REFERENCES TERM (TermID);
ALTER TABLE COURSE_SECTION ADD CONSTRAINT LocID_FK FOREIGN KEY (LocID) REFERENCES LOCATION (LocID);

ALTER TABLE TERM ADD CONSTRAINT Status_Check CHECK (Status IN ('OPEN', 'CLOSED'));

ALTER TABLE LOCATION ADD CONSTRAINT Room_Unique UNIQUE (Room);

SPOOL OFF;
