/ as sysdba
DROP USER c##lennin_Smidterm_Q1 CASCADE;
CREATE USER c##lennin_Smidterm_Q1 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO c##lennin_Smidterm_Q1;
ALTER USER c##lennin_Smidterm_Q1 QUOTA 100M on users;
CONNECT c##lennin_Smidterm_Q1/123;

SPOOL C:\Users\lenni\Escritorio\SPOOLexam.txt;

CREATE TABLE ADVISOR(
    AdvisorID NUMBER,
    AdvisorName VARCHAR(20) NOT NULL
);

ALTER TABLE ADVISOR
ADD CONSTRAINT AdvisorID_PK PRIMARY KEY(AdvisorID);

CREATE TABLE STUDENT(
    StudentID NUMBER,
    StudentName VARCHAR(20) NOT NULL,
    BirthDate DATE,
    AdvisorID NUMBER,
    Gender VARCHAR(1)
);

ALTER TABLE STUDENT
ADD CONSTRAINT StudentID_PK PRIMARY KEY(StudentID);

ALTER TABLE STUDENT
ADD CONSTRAINT AdvisorID_FK FOREIGN KEY(AdvisorID) REFERENCES ADVISOR (AdvisorID);

ALTER TABLE STUDENT
ADD CONSTRAINT Gender_Check CHECK (Gender IN ('M', 'F', 'm', 'f'));

CREATE TABLE COURSE(
    CourseID NUMBER,
    CourseTitle VARCHAR(20),
    Credits NUMBER CHECK(Credits > 0)
);

ALTER TABLE COURSE
ADD CONSTRAINT CourseID_PK PRIMARY KEY(CourseID);

ALTER TABLE COURSE
ADD CONSTRAINT CourseTitle_UNIQUE UNIQUE (CourseTitle);


CREATE TABLE ENROLLMENT(
    StudentID NUMBER,
    CourseID NUMBER,
    Grade NUMBER
);

ALTER TABLE ENROLLMENT
ADD CONSTRAINT StudentID_FK FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID);

ALTER TABLE ENROLLMENT
ADD CONSTRAINT CourseID_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID);

SPOOL OFF;