/ as sysdba
SELECT to_char(sysdate,'DD MM YYYY Year Month Day HH:MI:SS Am') FROM dual;
DROP USER c##lennin_L5Q1 CASCADE;
CREATE USER c##lennin_L5Q1 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO c##lennin_L5Q1;
ALTER USER c##lennin_L5Q1 QUOTA 100M on users;
CONNECT c##lennin_L5Q1/123;

CREATE TABLE COURSE(
    CourseID NUMBER,
    CourseName VARCHAR(10),
    Credits NUMBER
);

ALTER TABLE COURSE 
ADD CONSTRAINT CourseID_PK PRIMARY KEY (CourseID);

CREATE TABLE TERM(
    TermID NUMBER,
    Descriptionn VARCHAR(10)
);

ALTER TABLE TERM 
ADD CONSTRAINT TermID_PK PRIMARY KEY (TermID);

CREATE TABLE LOCATION(
    LocID NUMBER,
    Building VARCHAR(10),
    Room NUMBER
);

ALTER TABLE LOCATION 
ADD CONSTRAINT LocID_PK PRIMARY KEY (LocID);

CREATE TABLE STUDENT(
    StudID NUMBER,
    SName VARCHAR(10),
    Birthdate DATE
);

ALTER TABLE STUDENT 
ADD CONSTRAINT StudID_PK PRIMARY KEY (StudID);

CREATE TABLE ENROLLMENT(
    StudID NUMBER,
    CSectionID VARCHAR (10),
    GRADE NUMBER
);

ALTER TABLE ENROLLMENT 
ADD CONSTRAINT StudID_FK FOREIGN KEY (StudID) REFERENCES STUDENT (StudID);

ALTER TABLE ENROLLMENT 
ADD CONSTRAINT CSectionID_FK FOREIGN KEY (CSectionID) REFERENCES COURSE_SECTION (CSectionID);

CREATE TABLE COURSE_SECTION(
    CSectionID NUMBER,
    MaxCapacity NUMBER,
    CourseID NUMBER,
    TermID NUMBER,
    LocID NUMBER
);

