/ as sysdba

DROP USER c##user1  CASCADE;

CREATE USER c##user1 IDENTIFIED BY 123;

GRANT CONNECT, RESOURCE, DBA TO c##user1;


CONNECT c##user1/123

SPOOL C:\Users\lenni\Documentos\lasalle\DATABASES\SPOOL.txt;

SELECT to_char(sysdate,'DD MM YYYY Year Month Day HH:MI:SS Am') FROM dual;


CREATE TABLE FACULTY (
    FID NUMBER ,
    FName VARCHAR2(100),
    Salary NUMBER
);

CREATE TABLE STUDENT (
    StudentID NUMBER  ,
    StudentName VARCHAR2(100)
);

CREATE TABLE GRADE (
    StudentID NUMBER  ,
    CourseNo NUMBER  ,
    GRADE VARCHAR2(200)
);

CREATE TABLE COURSE (
    CourseNo NUMBER  ,
    CourseName VARCHAR2(200)
);

CREATE TABLE COURSE_SECTION (
    CourseNo NUMBER,
    CourseName VARCHAR2(200),
    SectionID NUMBER,
    FID NUMBER
    );


DESCRIBE FACULTY;
DESCRIBE STUDENT;
DESCRIBE GRADE;
DESCRIBE COURSE;
DESCRIBE COURSE_SECTION;



SPOOL OFF;


/*
DROP TABLE FACULTY;
DROP TABLE STUDENT;
DROP TABLE GRADE;
DROP TABLE COURSE;
DROP TABLE COURSE_SECTION;*/