/ as sysdba
DROP USER c##lennin_Smidterm_Q4 CASCADE;
CREATE USER c##lennin_Smidterm_Q4 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, DBA TO c##lennin_Smidterm_Q4;
ALTER USER c##lennin_Smidterm_Q4 QUOTA 100M on users;
CONNECT c##lennin_Smidterm_Q4/123;

SPOOL C:\Users\lenni\Escritorio\SPOOLexam4.txt;

CREATE SEQUENCE advisor_seq
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE ADVISOR(
    AdvisorID NUMBER,
    AdvisorName VARCHAR(20) NOT NULL,
    CONSTRAINT AdvisorID_PK PRIMARY KEY(AdvisorID)
);

CREATE SEQUENCE student_seq
  START WITH 1
  INCREMENT BY 1;


CREATE TABLE STUDENT(
    StudentID NUMBER,
    StudentName VARCHAR(20) NOT NULL,
    BirthDate DATE,
    AdvisorID NUMBER,
    Gender VARCHAR(1),
    CONSTRAINT StudentID_PK PRIMARY KEY(StudentID),
    CONSTRAINT AdvisorID_FK FOREIGN KEY(AdvisorID) REFERENCES ADVISOR (AdvisorID),
    CONSTRAINT Gender_Check CHECK (Gender IN ('M', 'F', 'm', 'f'))
);

CREATE TABLE COURSE(
    CourseID NUMBER,
    CourseTitle VARCHAR(20),
    Credits NUMBER CHECK(Credits > 0),
    CONSTRAINT CourseID_PK PRIMARY KEY(CourseID),
    CONSTRAINT CourseTitle_UNIQUE UNIQUE (CourseTitle)
);

CREATE SEQUENCE course_seq
  START WITH 1
  INCREMENT BY 1;


CREATE TABLE ENROLLMENT(
    StudentID NUMBER,
    CourseID NUMBER,
    Grade NUMBER,
    CONSTRAINT StudentID_FK FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
    CONSTRAINT CourseID_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID)
);

INSERT INTO ADVISOR VALUES(advisor_seq.NEXTVAL, 'Ramiro');
INSERT INTO STUDENT VALUES(student_seq.NEXTVAL, 'Lennin', TO_DATE('04/11/2003', 'MM/DD/YYYY'), advisor_seq.CURRVAL, 'M');
INSERT INTO COURSE VALUES(course_seq.NEXTVAL, 'Math', 20);
INSERT INTO ENROLLMENT VALUES(student_seq.CURRVAL, course_seq.CURRVAL, 7);


SPOOL OFF;